version: '3.7'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/app
    ports:
      - 80:80
      - 443:443

  backend:
    build: ./backend
    image: backend
    hostname: backend
    expose:
      - "8000"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    command: bash -c "gunicorn main:app --bind 0.0.0.0:8000 --access-logfile -"

  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-data:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  redis:
    image: redis:latest
    hostname: redis
    expose:
      - '6379'
    volumes:
      - 'redis-data:/data'

  rq_worker:
    image: backend
    env_file:
      - .env
    command: rq worker --url redis://redis

networks:
  default:
    name: app

volumes:
  mongodb-data:
  redis-data:
