version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/app
    ports:
      - 80:80

  backend:
    build: ./backend
    hostname: backend
    expose:
      - "8000"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    command: bash -c "gunicorn app:app --bind 0.0.0.0:8000"

  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-data:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

networks:
  default:
    name: app

volumes:
  mongodb-data: